import { Product } from "@/interfaces";
import Banner from "@components/client/Banner";
import ProductList from "@components/client/ProductList";
import Head from "next/head";
import { Metadata } from "next";

async function getProducts(): Promise<Product[]> {
    const res = await fetch("http://localhost:3000/api/products");
    // The return value is *not* serialized
    // You can return Date, Map, Set, etc.

    // Recommendation: handle errors
    if (!res.ok) {
        // This will activate the closest `error.js` Error Boundary
        throw new Error("Failed to fetch data");
    }

    return res.json();
}

const metadata: Metadata = {
    title: "FushionTech - Official Store",
    description: "Generated by Create Next App",
    icons: "/favicon.ico",
};
const HomePage = async () => {
    const products: Product[] = await getProducts();
    return (
        <>
            <main className="">
                <div className="max-w-contentContainer mx-auto">
                    <Banner />
                    <ProductList products={products} />
                </div>
            </main>
        </>
    );
};
export default HomePage;
