import { Product } from "@/interfaces";
import Banner from "@components/client/Banner";
import ProductList from "@components/client/ProductList";
import Head from "next/head";

async function getProducts(): Promise<Product[]> {
    const res = await fetch("http://localhost:3000/api/products");
    // The return value is *not* serialized
    // You can return Date, Map, Set, etc.

    // Recommendation: handle errors
    if (!res.ok) {
        // This will activate the closest `error.js` Error Boundary
        throw new Error("Failed to fetch data");
    }

    return res.json();
}

const HomePage = async () => {
    const products: Product[] = await getProducts();
    return (
        <>
            <Head>
                <title>FushionTech - Official Store</title>
                <meta
                    name="description"
                    content="Generated by Create Next App"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-lightBlue">
                <div className="max-w-contentContainer mx-auto bg-white">
                    <Banner />
                    <ProductList products={products} />
                </div>
            </main>
        </>
    );
};
export default HomePage;
